name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Package Build ğŸª›
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Installing Packages ğŸ“
        run: yarn install

      - name: Building Application ğŸ
        run: yarn build

  release:
    needs: build
    name: Creating a new release ğŸ€
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Reading JSON
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - run: echo ${{ steps.version.outputs.prop }}  # package.json version
      - run: echo ${{ github.event.head_commit.message }} # last commit message

      - name: Create Release âœ’ï¸
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.head_commit.message }} - v${{steps.version.outputs.prop}}
          tag_name: v${{ steps.version.outputs.prop }}
          token: ${{ secrets.PAT }}